apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemdeployment
  labels:
    app: menuitem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuitem  
  template:
    metadata:
      labels:
        app: menuitem
    spec:
      containers:
      - name: menuitem
        image: docker pull menuitemlistingacr.azurecr.io/menuitemlistingrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myacrcredentials
---
apiVersion: v1
kind: Service
metadata:
  name: menuitemsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: menuitem